lab_1/urls.py
from django.urls import re_path
from .views import index
from django.conf import settings
from django.conf.urls.static import static
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

mysite/urls.py
from django.urls import path
from .views import *

app_name = 'mysite'
urlpatterns = [
	path('',index, name='index'),
	path('main/',mainpage, name='mainpage'),
    path('registration/',registration, name='registration'),
    path('schedule_form/',schedule_form,name='schedule_form'),
    path('schedule_reset/',schedule_reset,name='schedule_reset'),
    path('schedule/',schedule_view, name='schedule_view'),
]

praktikum/urls.py
from django.conf.urls import include
from django.conf import settings
from django.urls import path
from django.contrib import admin
from lab_1.views import index as index_lab1
from django.conf.urls.static import static
import mysite.urls as mysite

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    path('',include(mysite)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

mysite/models.py
from django.db import models
from datetime import date,time

# Create your models here.
class Schedule(models.Model):
	date = models.DateField()
	time = models.TimeField()
	event = models.CharField(max_length=25)
	venue = models.CharField(max_length=50)
	category = models.CharField(max_length=10)

mysite/forms.py
from django import forms

class Schedule_Form(forms.Form):

	date = forms.DateField(label='Date', required=True, widget=forms.DateInput(attrs={'type' : 'date'}))
	time = forms.TimeField(label='Time', required=True, widget=forms.TimeInput(attrs={'type' : 'time'}))
	event = forms.CharField(label='Event', required=True, max_length=25)
	venue = forms.CharField(label='Venue', required=True, max_length=50)
	category = forms.CharField(label='Category', required=True, max_length=10)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Rafif Taris' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1999,6,2) #TODO Implement this, format (Year, Month, Date)
npm = 1706979436 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

mysite/views.py
from django.shortcuts import render,redirect
from .models import Schedule
from .forms import Schedule_Form

# Create your views here.
def index(request):
    return render(request,'Story03WelcomePage.html',{})

def mainpage(request):
	return render(request,'Story03.html',{})	

def registration(request):
	return render(request,'Story03Challenge.html',{})

# def schedule_form(request):
# 	return render(request,'ScheduleForm.html',{})

def schedule_form(request):
	form = Schedule_Form(request.POST or None)
	response = {}
	if (request.method == 'POST'):
		if(form.is_valid()):
			response['event'] = request.POST.get("event")
			response['date'] = request.POST.get("date")
			response['time'] = request.POST.get("time")
			response['venue'] = request.POST.get("venue")
			response['category'] = request.POST.get("category")
			schedule = Schedule(date=response['date'],time=response['time'],event=response['event'],venue=response['venue'],category=response['category'])
			schedule.save()
	
	response['form'] = form
	return render(request,"ScheduleForm.html", response)		
			


def schedule_view(request):
	schedule = Schedule.objects.all()
	response = {
		"jadwal" : schedule
	}
	return render(request, 'ScheduleView.html', response)

def schedule_reset(request):
	Schedule.objects.all().delete()
	return render(request, 'ScheduleView.html', {})

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
	
	.header{
		background: linear-gradient(#123BAB,#36599B);
		padding: 50px;
		text-align: center;
	}

	.main{
		float: left;
		width: 55%;
		padding: 15px;
		margin-top: 7px;
	}
	

	.info{
		background: linear-gradient(#FE7800,#FF9333) ;
		float: right;
		width: 35%;
		padding: 10px;
		margin-top: 20px;
		text-align: center;
	}

	.responsive{
		max-width: : 100%;	
		width: auto;
	}

	.cropping{
		width: 400px;
		height: 400px;
		object-fit: cover;
	}

	@media screen and (max-width: 800px){
		.main, .info, .responsives{
			width: 90%
		}
	}

	@media only screen and (max-width:620px) {
 	 /* For mobile phones: */
  		.main, .info, .responsive {
    		width:100%;
  		}
	}

	@media only screen and (max-width:400px) {
 	 /* For mobile phones: */
  		.main, .info, .responsive {
    		width:100%;
  		}
	}

	</style>
	<title>The Adventure of Rafif Taris</title>
</head>
<body style="background-color: #02CC1B;">
	<div class='header'>
		<h1><font color = #FFFFFF>Welcome to My Journey!</font></h1>
		<h2>
	</div>

	<div class="main">
		<font color = #FFFFFF>
		<h2>Story of My Life</h2>
		<p>Nama		: {{ name }} </p>
		<p>NPM		: {{ npm }} </p>
		<p>Umur		: {{ age }} tahun </p>
		<p>Kuliah	: Faculty of Computer Science University of Indonesia</p>
		<p>Hobi		: Mendengarkan Musik, Main Game, Membaca Novel</p>
		<p></p>
		<p>Saya suka mendengarkan musik terutama genre K-Pop dan EDM. Saya masuk Fasilkom UI karena saya ingin mendalami sistem keamanan komputer. Menjadi programmer web adalah salah satu langkah menuju impian saya. See you on top guys!</p>
		</font>
	</div>

	<div class="info responsive">
		<font color = #FFFFFF>
		<h2>My Photo</h2>
		<img src="http://www.about.tarung2017.com/foto/329.jpg" alt="Profile Picture" class='cropping responsive'>
		<p></p>
		<img src="https://scontent.fcgk10-1.fna.fbcdn.net/v/t1.0-9/40844951_2078756502175899_3138172950662873088_n.jpg?_nc_cat=0&oh=3620980e84dc130cacaa0ddaec06e3bd&oe=5BF0D0E2" alt="Profile Picture 2" class='responsive cropping'>
		</font>
	</div>

</body>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

mysite/templates/ScheduleForm.html
{% extends 'logoNavbar.html' %}

{% block content %}
<br>
<section name="form" style="text-align: center;">
		<p style="text-align: center; font-size: 30px;">~ Schedule Form ~</p><br>
		<form id="form" method="POST" action="{% url 'mysite:schedule_form' %}">
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group">
			    <label for="exampleInputName1">{{ field.label }}<br>
			    {{ field }}
			    </label>
			</div>
			{% endfor %}
			<br>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
</section>
{% endblock %}

mysite/templates/ScheduleView.html
{% extends 'logoNavbar.html' %}

{% load static %}
{% block content %}
<br>
<p style="text-align: center; font-size: 30px;">~ My Schedule ~</p>
<br>

	{% if jadwal %}
		<div style="text-align: center;">
			<button type="button" class="btn btn-danger" onclick="location.href='{% url 'mysite:schedule_reset' %}'">Delete Schedule</button>
		</div>
		{% for acara in jadwal %}
		<br>
		<div class='rcorners1'>
			<br>
			<p>&ensp;{{ acara.event }}</p>
			<p>&ensp;Date     : {{ acara.date }}</p>
			<p>&ensp;Time     : {{ acara.time }}</p>
			<p>&ensp;Venue    : {{ acara.venue }}</p>
			<p>&ensp;Category : {{ acara.category }}</p>
		</div>
		{% endfor %}
	{% else %}
	<br><br>
	<p style="text-align: center;font-size: 30px;">Belum ada jadwal</p>
	{% endif %}

{% endblock %}

mysite/templates/Story03.html
{% extends 'logoNavbar.html' %}
{% load static %}

{% block content %}

	<br>
	<div class="rcorners1" class="container-fluid">	
		<img src="{% static 'ProfilePhoto.jpg' %}" id="ProfilePhoto">
		<p style="padding: 30px">Hello, I'm &ensp;<span style="font-family: 'Rock Salt', cursive;">Rafif Taris</span><br>
			<span style="font-size: 20px"> A self-reliant man with an imaginative mind. Currently studying web programming and developing my skills. I am striving for better life achievements and also trying to be genuine and considerate person.</p>
	</div>
	<br><br>
		<div class="rcorners2">
			<br>		
			<p class="subtitle">&ensp;Experience</p>
			<svg height="10" width="125">
	  		<line x1="14" y1="0" x2="125" y2="0" style="stroke:#56CCF2 ;stroke-width:20;" />
	  		Sorry, your browser does not support inline SVG.
			</svg>
			<ul class="list-unstyled">
			  <li class="media my-4">
			    <img class="align-self-center mr-3 eventLogo" src="{% static 'Betis.jpg' %}" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">Staff of Public Relation and Partnership BETIS 2018</h5>
			    </div>
			  </li>
			  <li class="media my-4">
			   	<img class="align-self-center mr-3 eventLogo" src="{% static 'CGT.jpg' %}" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">Staff of Bazaar CGT 2018</h5>
			    </div>
			  </li>
			  <li class="media my-4">
			    <img class="align-self-center mr-3 eventLogo" src="{% static 'keilmuan.png' %}" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">Staff of Science Department BEM Fasilkom UI 2018</h5>
			    </div>
			  </li>
			  <li class="media my-4">
			    <img class="align-self-center mr-3 eventLogo" src="{% static 'Wisgen.jpg' %}" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">Staff of Liaison Officer Wisuda Genap 2018</h5>
			    </div>
			  </li>
			  <li class="media my-4">
			    <img class="align-self-center mr-3 eventLogo" src="{% static 'OpenHouse.jpg' %}" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">Staff of Creative Open House Fasilkom UI 2018</h5>
			    </div>
			  </li>
			</ul>


		</div>

		<div class="rcorners3">
			<br>
			<p class="subtitle">&ensp;Education</p>
			<svg height="10" width="125">
	  		<line x1="14" y1="0" x2="115" y2="0" style="stroke:#56CCF2 ;stroke-width:20;" />
	  		Sorry, your browser does not support inline SVG.
			</svg>
			<ul class="list-unstyled">
			  <li class="media my-4">
			    <img class="align-self-center mr-3 eduLogo" src="https://pbs.twimg.com/media/Dnd6KCaUcAA1VeY.png" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">SD Kartika VIII/I</h5>
			    </div>
			  </li>
			  <li class="media my-4">
			   	<img class="align-self-center mr-3 eduLogo" src="https://pbs.twimg.com/media/Dnd6KCpVYAAHv-P.jpg" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">SMPN 49 Jakarta</h5>
			    </div>
			  </li>
			  <li class="media my-4">
			    <img class="align-self-center mr-3 eduLogo" src="https://pbs.twimg.com/media/Dnd6KCLU8AEFCoS.jpg" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">SMAN 39 Jakarta</h5>
			    </div>
			  </li>
			  <li class="media my-4">
			    <img class="align-self-center mr-3 eduLogo" src="https://pbs.twimg.com/media/Dnd6KCdUYAALk4U.png" alt="Generic placeholder image">
			    <div class="media-body">
			      <h5 style="font-family: 'Reem Kufi', sans-serif;">Fasilkom UI</h5>
			    </div>
			  </li>
			</ul>
		</div>

		<div class="rcorners3" style="margin-top: 30px;">
			<br>
			<p class="subtitle">&ensp;Skills</p>
			<svg height="10" width="125">
	  		<line x1="14" y1="0" x2="62" y2="0" style="stroke:#56CCF2 ;stroke-width:20;" />
	  		Sorry, your browser does not support inline SVG.
			</svg>
			<br><br>	
			<p style="margin-left:5%; font-size: 20px;">Teamworking</p><br><br>
			<p style="margin-left:50%; font-size: 20px;">Time Management</p><br><br>
			<p style="margin-left:5%; font-size: 20px;">Multitasking</p><br><br>
			
		</div>

	

	<div class="rcorners1 quoteBox">
		<p id="quote"><br><br>Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind.<br>- Dr. Seuss</p>
	</div>
	{% endblock %}	
	{% block footer %}
			<br>
    		<h2 style="text-align: center;color: white">Or you can register your account here!</h2><br>
			<a href="{% url 'mysite:registration' %}" type="button" class="btn btn-light btn-lg registerButton">
				<p style="font-size: 20px;margin-top: 10%;">&ensp;Register&ensp;
				 <svg height="100" width="50">
	 			 	<polygon points="0,0 35,50 0,100 20, 50"  style="fill:#107551;stroke-width:1;float: right;" />
				 </svg> 
				</p>
			</a>
	{% endblock %}

mysite/templates/Story03Challenge.html
{% extends 'logoNavbar.html' %}
{% load static %}

{% block content %}

	<br>
	<p style="text-align: center; font-size: 30px;">~ Registration Form ~</p>
	<div style="text-align: center; display: none; font-size: 20px" id="thanks">Thank you for registering yourself at this website!</div><br>
	<form style="text-align: center;">
	  <div class="form-group">
	    <label for="exampleInputName1">Nama</label>
	    <input type="text" class="form-control" id="exampleInputName1" placeholder="Nama" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputDate1">Tanggal Lahir</label>
	    <input type="date" class="form-control" id="exampleInputDate1" aria-describedby="dateHelp" placeholder="dd/mm/yyyy" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputEmail1">Email Address</label>
	    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" style="width: 30%; margin: 0% 35% 0% 35%;">
	    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
	  </div>
	  <div class="form-group">
	    <label for="exampleInputUsername1">Username</label>
	    <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Username" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password</label>
	    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password Confirmation</label>
	    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password Confirmation" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <button type="submit" class="btn btn-primary" style="margin-left: 0.2%" onclick="appear()">Submit</button>
	</form>

	<script type="text/javascript">
		function appear(){
			document.getElementById("thanks").display = block;
		}
	</script>
	<br><br>
{% endblock %}

mysite/templates/Story03WelcomePage.html
{% extends 'logoNavbar.html' %}
{% load static %}

{% block content %}

	<br>
	<div>
		<h1 style="font-family: 'Playball', cursive; text-align: center; font-size: 10vw;">Welcome!</h1>
	</div>
	<div>
		<img src="https://pbs.twimg.com/media/DnfVh_NVsAA307u.jpg" class="welcomeimg">
	</div>
	<br><br><br>
	<div class="container">
    		<div class="container">
			  <div class="row">
			    <div class="col-sm">
			      	<a href="{% url 'mysite:mainpage' %}" type="button" class="btn btn-light btn-lg welcomebutton" style="margin-bottom: 5%">
						<p class="buttondesc">&ensp;About Me&ensp;
						 <svg height="100" width="50">
			 			 	<polygon points="0,0 35,50 0,100 20, 50"  style="fill:#107551;stroke-width:1;float: right;" />
						 </svg> 
						</p>
					</a>
			    </div>
			    <div class="col-sm">
			      	<a href="{% url 'mysite:registration' %}" type="button" class="btn btn-light btn-lg welcomebutton">
						<p class="buttondesc">&ensp;Register Yourself&ensp;
						 <svg height="100" width="50">
			 			 	<polygon points="0,0 35,50 0,100 20, 50"  style="fill:#107551;stroke-width:1;float: right;" />
						 </svg> 
						</p>
					</a>
			    </div>
			</div>
		</div>
	</div>
{% endblock %}

mysite/templates/logoNavbar.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Rafif's Website</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'Story03Style.css' %}">	
	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
</head>

<body style="height: ">	
    <!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand active" href="{% url 'mysite:index' %}"> <img src="{% static "Logo.png" %}" style="width:50px;"><span class="sr-only">(current)</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  	<span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  	<ul class="navbar-nav mr-auto">
				<li class="nav-item">
			 		 <a class="nav-link" href="{% url 'mysite:mainpage' %}">Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:registration' %}">Message Me</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:schedule_form' %}">Add Schedule</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:schedule_view' %}">My Schedule</a>
			  	</li>
		  	</ul>
		</div>
	</nav>

	<div style="text-align: center;">
		<a href="{% url 'index' %}">
			<img src="{% static 'Logo.png' %}" class="logo">	
		</a>
	</div>
    {% block content %}
    {% endblock %}
    <div class="jumbotron" style="margin-top: 50px; margin-bottom: 0px;background-color: #27A275;height: 7%;">
  		<div class="container">
    		<h2 style="text-align: center;color: white">Want to know more about me?</h2>
    		<svg height="10" width="70%" style="margin-left: 1%;">
	  		<line x1="45%" y1="0" x2="95%" y2="0" style="stroke:#56CCF2 ;stroke-width:20;" />
	  		Sorry, your browser does not support inline SVG.
			</svg>
			<br><br>
    		<div class="container">
			  	<div class="row">
			    	<div class="col-sm">
			      		<img src="https://pbs.twimg.com/media/DnfEqdBVAAAIeiD.png" class="align-self-center mr-3 socmedLogo">
			      		<p id="socmedID">@rafiftaris</p>
			    	</div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqdCV4AAjnr0.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">@rafiftaris</p>
				    </div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqczUcAEE1A-.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">rafiftaris1@gmail.com</p>
				    </div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqdBV4AA73Jp.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">Rafif Taris</p>
				    </div>
				</div>
				{% block footer %}
				{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>